name: Android CI 

on:
  pull_request:
      branches-ignore:
      - 'l10n_*'
  push:
    branches-ignore:
      - 'l10n_*'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
        repository: PojavLauncherTeam/gl4es 
        path: gl4es

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build latest GL4ES
      continue-on-error: true
      run: |
        cd gl4es
        git remote add upstream https://github.com/ptitSeb/gl4es
        git fetch upstream
        git checkout master
        git merge upstream/main || echo "Merge exit code $?"
        export ANDROID_NDK_HOME="$ANDROID_SDK_ROOT/ndk-bundle"
        $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. APP_BUILD_SCRIPT=./Android.mk
        cp -R libs/* ../app_pojavlauncher/src/main/jniLibs/
        
    - name: Build APK with Gradle
      run: |
        chmod +x scripts/languagelist_updater.sh
        bash scripts/languagelist_updater.sh
      
        mkdir -p out
        chmod +x gradlew
        ./gradlew clean

        # Build JRE JAR files (security manager, etc...)
        ./gradlew :jre_lwjgl3glfw:build
        # mkdir app_pojavlauncher/src/main/assets/components/internal_libs
        rm app_pojavlauncher/src/main/assets/components/lwjgl3/lwjgl-glfw-classes.jar
        cp jre_lwjgl3glfw/build/libs/jre_lwjgl3glfw-3.2.3.jar app_pojavlauncher/src/main/assets/components/lwjgl3/lwjgl-glfw-classes.jar
        
        # Build the launcher
        ./gradlew :app_pojavlauncher:assembleDebug
        mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug.apk
        # mv app_pojavlauncher/build/intermediates/merged_native_libs/debug/out/lib out/debug_lib

    - name: Build APK without runtime
      run: | 
        rm -r app_pojavlauncher/src/main/assets/components/jre
        ./gradlew assembleDebug
        mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug-noruntime.apk

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: out/app-debug.apk

    - name: Upload APK (without runtime)
      uses: actions/upload-artifact@v2
      with:
          name: app-debug-noruntime
          path: out/app-debug-noruntime.apk

