name: Android CI

on:
  pull_request:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  push:
    branches-ignore:
      - 'l10n_v3_openjdk2'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      GPLAY_KEYSTORE_PASSWORD: ${{ secrets.GPLAY_KEYSTORE_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Get gl4es
      uses: dawidd6/action-download-artifact@v2
      with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: android.yml
          path: app_pojavlauncher/src/main/jniLibs
          workflow_conclusion: success
          repo: PojavLauncherTeam/gl4es-114-extra
          branch: master
          name: gl4es-114
    
    - name: Get JRE8
      uses: dawidd6/action-download-artifact@v2
      with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          path: app_pojavlauncher/src/main/assets/components/jre
          workflow_conclusion: success
          repo: PojavLauncherTeam/android-openjdk-build-multiarch
          branch: buildjre8
          name: jre8-pojav
    
    - name: Build JRE JAR files
      run: |
        chmod +x scripts/languagelist_updater.sh
        bash scripts/languagelist_updater.sh
      
        mkdir -p out
        chmod +x gradlew
        ./gradlew clean
        # Build JRE JAR files (security manager, etc...)
        ./gradlew :jre_lwjgl3glfw:build
        
    - name: Build Google Play .aab
      if: github.repository_owner == 'PojavLauncherTeam' && github.ref_name == 'v3_openjdk'
      run: |
        ./gradlew :app_pojavlauncher:bundleGplay
        mv app_pojavlauncher/build/outputs/bundle/gplay/app_pojavlauncher-gplay.aab out/app-gplay.aab
    
    - name: Build Debug .apk
      run: |
        # Build the launcher
        ./gradlew :app_pojavlauncher:assembleDebug
        mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug.apk
        
    - name: Build APK without runtime
      run: | 
        rm -r app_pojavlauncher/src/main/assets/components/jre
        ./gradlew assembleDebug
        mv app_pojavlauncher/build/outputs/apk/debug/app_pojavlauncher-debug.apk out/app-debug-noruntime.apk
        
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
          name: app-debug
          path: out/app-debug.apk
          
    - name: Upload onto the Google Play testing track
      if: github.repository_owner == 'PojavLauncherTeam' && github.ref_name == 'v3_openjdk'
      uses: r0adkll/upload-google-play@v1.0.15
      with:
        serviceAccountJsonPlainText: ${{ secrets.GPLAY_SERVICE_JSON }}
        packageName: net.kdt.pojavlaunch
        releaseFiles: out/app-gplay.aab
        track: internal
        inAppUpdatePriority: 5
        
    - name: Upload APK (without runtime)
      uses: actions/upload-artifact@v2
      with:
          name: app-debug-noruntime
          path: out/app-debug-noruntime.apk
